### ISSUE TITLE
ModuleNotFoundError when importing nite2

### ISSUE THREAD

**Issue by CalciferZh** [severin-lemaignan/openni-python#2]
When I tried to import `nite2`, a ModuleNotFoundError occurred:
```
>>> from openni import nite2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\openni-2.2.0.post6-py3.6.egg\openni\nite2.py", line 9, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\openni-2.2.0.post6-py3.6.egg\openni\_nite2.py", line 26, in <module>
ModuleNotFoundError: No module named '_openni2'
```
My enviroment is `Python 3.6.2 :: Anaconda custom (64-bit)` under Windows 10. Both the version installed from here(GitHub) and pypi have this problem. Any hints?
Thanks a lot for help.

**Comment by natthapach** [comment]
I have same problem. Did you find solution?

**Comment by pcp16** [comment]
It seems this issue has to do with Python 2 vs 3, as it works fine in Python 2.7.
